/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as FontsRouteImport } from './routes/fonts'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as LangDocsRouteRouteImport } from './routes/$lang.docs.route'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'
import { Route as LangDocsSplatRouteImport } from './routes/$lang.docs.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsRoute = FontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsRouteRoute = LangDocsRouteRouteImport.update({
  id: '/$lang/docs',
  path: '/$lang/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangDocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/fonts': typeof FontsRoute
  '/images': typeof ImagesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$lang/docs': typeof LangDocsRouteRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes/': typeof ResumesIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/fonts': typeof FontsRoute
  '/images': typeof ImagesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$lang/docs': typeof LangDocsRouteRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes': typeof ResumesIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/fonts': typeof FontsRoute
  '/images': typeof ImagesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$lang/docs': typeof LangDocsRouteRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes/': typeof ResumesIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/fonts'
    | '/images'
    | '/settings'
    | '/templates'
    | '/$lang/docs'
    | '/docs/$'
    | '/resumes/$resumeId'
    | '/resumes/'
    | '/$lang/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/fonts'
    | '/images'
    | '/settings'
    | '/templates'
    | '/$lang/docs'
    | '/docs/$'
    | '/resumes/$resumeId'
    | '/resumes'
    | '/$lang/docs/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/fonts'
    | '/images'
    | '/settings'
    | '/templates'
    | '/$lang/docs'
    | '/docs/$'
    | '/resumes/$resumeId'
    | '/resumes/'
    | '/$lang/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  FontsRoute: typeof FontsRoute
  ImagesRoute: typeof ImagesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  LangDocsRouteRoute: typeof LangDocsRouteRouteWithChildren
  DocsSplatRoute: typeof DocsSplatRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts': {
      id: '/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof FontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs': {
      id: '/$lang/docs'
      path: '/$lang/docs'
      fullPath: '/$lang/docs'
      preLoaderRoute: typeof LangDocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof LangDocsRouteRoute
    }
  }
}

interface LangDocsRouteRouteChildren {
  LangDocsSplatRoute: typeof LangDocsSplatRoute
}

const LangDocsRouteRouteChildren: LangDocsRouteRouteChildren = {
  LangDocsSplatRoute: LangDocsSplatRoute,
}

const LangDocsRouteRouteWithChildren = LangDocsRouteRoute._addFileChildren(
  LangDocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  FontsRoute: FontsRoute,
  ImagesRoute: ImagesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  LangDocsRouteRoute: LangDocsRouteRouteWithChildren,
  DocsSplatRoute: DocsSplatRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  ResumesIndexRoute: ResumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
